/-
Copyright (c) 2026 Alessandro Iraci, Aristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alessandro Iraci, Aristotle (Harmonic)
-/
module

public import Mathlib.Combinatorics.Young.RobinsonSchensted.Injective

/-!
# The plactic monoid

A Lean 4 port of the beginning of `theories/LRrule/plactic.v` from
[Coq-Combi](https://github.com/math-comp/Coq-Combi).

Two words are *Knuth equivalent* (plactic congruent) when one can be obtained from the
other by a sequence of elementary Knuth transformations

* `x z y ↦ z x y` for `x ≤ y < z`,
* `y x z ↦ y z x` for `x < y ≤ z`,

applied inside a word.  The main result of this file is that every word is Knuth
equivalent to the reading word of its Robinson–Schensted insertion tableau (Coq
`congr_RS`), so that words with the same insertion tableau are Knuth equivalent.

## Main definitions

* `List.PlacticStep` : one elementary Knuth transformation.
* `List.PlacticEquiv` : the equivalence relation generated by them (Coq `plactcongr`).

## Main results

* `List.plactic_insRow` : the bumped letter followed by the new row is Knuth equivalent
  to the row followed by the inserted letter.
* `List.plactic_toWord_RS` : a word is Knuth equivalent to the reading word of its
  insertion tableau (Coq `congr_RS`).
* `List.plactic_of_RS_eq` : words with the same insertion tableau are Knuth equivalent.
-/

@[expose] public section

namespace List

open List

variable {T : Type*} [LinearOrder T]

/-! ### Knuth transformations -/

/-- An elementary Knuth transformation, applied inside a word. -/
inductive PlacticStep : List T → List T → Prop
  | knuthAC {x y z : T} (hxy : x ≤ y) (hyz : y < z) (u v : List T) :
      PlacticStep (u ++ x :: z :: y :: v) (u ++ z :: x :: y :: v)
  | knuthCA {x y z : T} (hxy : x < y) (hyz : y ≤ z) (u v : List T) :
      PlacticStep (u ++ y :: x :: z :: v) (u ++ y :: z :: x :: v)

/-- Knuth equivalence (plactic congruence): the equivalence relation generated by the
elementary Knuth transformations (Coq `plactcongr`). -/
def PlacticEquiv : List T → List T → Prop := Relation.EqvGen PlacticStep

lemma PlacticEquiv.refl (u : List T) : PlacticEquiv u u := Relation.EqvGen.refl u

lemma PlacticEquiv.symm {u v : List T} (h : PlacticEquiv u v) : PlacticEquiv v u :=
  Relation.EqvGen.symm _ _ h

lemma PlacticEquiv.trans {u v w : List T} (h1 : PlacticEquiv u v) (h2 : PlacticEquiv v w) :
    PlacticEquiv u w := Relation.EqvGen.trans _ _ _ h1 h2

lemma PlacticStep.plactic {u v : List T} (h : PlacticStep u v) : PlacticEquiv u v :=
  Relation.EqvGen.rel _ _ h

lemma PlacticStep.append_left (c : List T) {u v : List T} (h : PlacticStep u v) :
    PlacticStep (c ++ u) (c ++ v) := by
  cases h with
  | knuthAC hxy hyz a b =>
    simpa [← List.append_assoc] using PlacticStep.knuthAC hxy hyz (c ++ a) b
  | knuthCA hxy hyz a b =>
    simpa [← List.append_assoc] using PlacticStep.knuthCA hxy hyz (c ++ a) b

lemma PlacticStep.append_right (c : List T) {u v : List T} (h : PlacticStep u v) :
    PlacticStep (u ++ c) (v ++ c) := by
  cases h with
  | knuthAC hxy hyz a b =>
    simpa [List.append_assoc] using PlacticStep.knuthAC hxy hyz a (b ++ c)
  | knuthCA hxy hyz a b =>
    simpa [List.append_assoc] using PlacticStep.knuthCA hxy hyz a (b ++ c)

lemma PlacticEquiv.append_left (c : List T) {u v : List T} (h : PlacticEquiv u v) :
    PlacticEquiv (c ++ u) (c ++ v) := by
  induction h with
  | rel x y hxy => exact (hxy.append_left c).plactic
  | refl x => exact PlacticEquiv.refl _
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih1 ih2 => exact ih1.trans ih2

lemma PlacticEquiv.append_right (c : List T) {u v : List T} (h : PlacticEquiv u v) :
    PlacticEquiv (u ++ c) (v ++ c) := by
  induction h with
  | rel x y hxy => exact (hxy.append_right c).plactic
  | refl x => exact PlacticEquiv.refl _
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih1 ih2 => exact ih1.trans ih2

/-- A Knuth transformation permutes the letters of a word. -/
lemma PlacticStep.perm {u v : List T} (h : PlacticStep u v) : u.Perm v := by
  cases h with
  | knuthAC hxy hyz a b =>
    exact List.Perm.append_left a (List.Perm.swap _ _ _)
  | knuthCA hxy hyz a b =>
    exact List.Perm.append_left a ((List.Perm.swap _ _ _).cons _)

/-- Knuth equivalent words are permutations of each other (Coq `plactcongr_homog`). -/
lemma PlacticEquiv.perm {u v : List T} (h : PlacticEquiv u v) : u.Perm v := by
  induction h with
  | rel x y hxy => exact hxy.perm
  | refl x => exact List.Perm.refl x
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih1 ih2 => exact ih1.trans ih2

lemma PlacticEquiv.cons (a : T) {u v : List T} (h : PlacticEquiv u v) :
    PlacticEquiv (a :: u) (a :: v) := by
  simpa using h.append_left [a]

/-! ### Knuth equivalence and row insertion -/

/-- A letter can be moved to the end of a row it is smaller than. -/
lemma plactic_cons_shift : ∀ (r : List T) (a l : T), IsRow r → l < a → (∀ y ∈ r, a ≤ y) →
    PlacticEquiv (a :: l :: r) (a :: (r ++ [l])) := by
  intro r
  induction r with
  | nil => intro a l _ _ _; simpa using PlacticEquiv.refl [a, l]
  | cons y r ih =>
    intro a l hr hla hay
    have hay0 : a ≤ y := hay y List.mem_cons_self
    have hyr : ∀ z ∈ r, y ≤ z := by
      have hp := hr
      rw [IsRow, List.isChain_iff_pairwise, List.pairwise_cons] at hp
      exact hp.1
    have hstep : PlacticStep (a :: l :: y :: r) (a :: y :: l :: r) := by
      simpa using PlacticStep.knuthCA hla hay0 [] r
    refine hstep.plactic.trans ?_
    have h1 : PlacticEquiv (y :: l :: r) (y :: (r ++ [l])) :=
      ih y l hr.of_cons (lt_of_lt_of_le hla hay0) hyr
    simpa using h1.cons a

/-- The first entry of a row after insertion is at most the inserted letter. -/
lemma headD_insRow_le (r : List T) (l d : T) : (insRow r l).headD d ≤ l := by
  cases r with
  | nil => simp
  | cons x r =>
    by_cases hx : l < x
    · rw [insRow_cons, ite_eq_left hx]
      simp
    · rw [insRow_cons, ite_eq_right hx]
      simpa using not_lt.1 hx

lemma insRow_ne_nil (r : List T) (l : T) : insRow r l ≠ [] := by
  intro h
  have hlen : (insRow r l).length = max r.length (insPos r l + 1) := insRow_length r l
  rw [h] at hlen
  simp at hlen
  omega

/-- Coq `plact_row_insert`: the letter bumped out of a row, followed by the row after
insertion, is Knuth equivalent to the row followed by the inserted letter. -/
lemma plactic_insRow {r : List T} (hr : IsRow r) {l b : T} (hb : bumped r l = some b) :
    PlacticEquiv (b :: insRow r l) (r ++ [l]) := by
  induction r with
  | nil => rw [bumped] at hb; simp at hb
  | cons x r ih =>
    have hrow : IsRow r := hr.of_cons
    have hx : ∀ y ∈ r, x ≤ y := by
      have hp := hr
      rw [IsRow, List.isChain_iff_pairwise, List.pairwise_cons] at hp
      exact hp.1
    by_cases hlx : l < x
    · have hbx : b = x := by
        rw [bumped_cons, ite_eq_left hlx] at hb
        exact (Option.some.inj hb).symm
      rw [hbx, insRow_cons, ite_eq_left hlx]
      simpa using plactic_cons_shift r x l hrow hlx hx
    · have hxl : x ≤ l := not_lt.1 hlx
      rw [bumped_cons, ite_eq_right hlx] at hb
      rw [insRow_cons, ite_eq_right hlx]
      obtain ⟨u0, rest, hins⟩ : ∃ u0 rest, insRow r l = u0 :: rest := by
        cases hcase : insRow r l with
        | nil => exact absurd hcase (insRow_ne_nil r l)
        | cons u0 rest => exact ⟨u0, rest, rfl⟩
      have hu0l : u0 ≤ l := by
        have hle := headD_insRow_le r l u0
        rw [hins] at hle
        simpa using hle
      have hxu0 : x ≤ u0 := by
        rcases mem_insRow (r := r) (l := l) (y := u0) (by rw [hins]; exact List.mem_cons_self)
          with hmem | rfl
        · exact hx u0 hmem
        · exact hxl
      have hu0b : u0 < b := lt_of_le_of_lt hu0l (lt_of_bumped hb)
      have hstep : PlacticStep (x :: b :: u0 :: rest) (b :: x :: u0 :: rest) := by
        simpa using PlacticStep.knuthAC hxu0 hu0b [] rest
      have h1 : PlacticEquiv (b :: insRow r l) (r ++ [l]) := ih hrow hb
      rw [hins]
      refine (hstep.plactic.symm).trans ?_
      have h2 : PlacticEquiv (x :: (b :: insRow r l)) (x :: (r ++ [l])) := h1.cons x
      rw [hins] at h2
      simpa using h2

/-! ### Knuth equivalence and the insertion tableau -/

/-- Coq `congr_RS` (inner step): inserting a letter in a tableau changes its reading word
into a Knuth equivalent word. -/
theorem plactic_toWord_insTab {t : List (List T)} (h : IsTableau t) (l : T) :
    PlacticEquiv (toWord (insTab t l)) (toWord t ++ [l]) := by
  induction t generalizing l with
  | nil => simpa [toWord] using PlacticEquiv.refl [l]
  | cons t0 t ih =>
    obtain ⟨-, hrow, -, htab⟩ := h
    cases hb : bumped t0 l with
    | none =>
      rw [insTab_cons_of_bumped_none hb, toWord_cons, toWord_cons,
        insRow_eq_append_of_bumped_none hb, ← List.append_assoc]
      exact PlacticEquiv.refl _
    | some b =>
      rw [insTab_cons_of_bumped_some hb, toWord_cons, toWord_cons]
      have h1 : PlacticEquiv (toWord (insTab t b) ++ insRow t0 l)
          ((toWord t ++ [b]) ++ insRow t0 l) := (ih htab b).append_right _
      refine h1.trans ?_
      have h2 : PlacticEquiv (toWord t ++ (b :: insRow t0 l)) (toWord t ++ (t0 ++ [l])) :=
        (plactic_insRow hrow hb).append_left _
      simpa [List.append_assoc] using h2

/-- Coq `congr_RS`: a word is Knuth equivalent to the reading word of its insertion
tableau. -/
theorem plactic_toWord_RS (w : List T) : PlacticEquiv (toWord (RS w)) w := by
  induction w using List.reverseRecOn with
  | nil => exact PlacticEquiv.refl _
  | append_singleton w l ih =>
    rw [RS_concat]
    exact (plactic_toWord_insTab (isTableau_RS w) l).trans (ih.append_right [l])

/-- Words with the same insertion tableau are Knuth equivalent. -/
theorem plactic_of_RS_eq {w w' : List T} (h : RS w = RS w') : PlacticEquiv w w' := by
  refine ((plactic_toWord_RS w).symm).trans ?_
  rw [h]
  exact plactic_toWord_RS w'

end List
